import type { Metadata } from "next";
import "./globals.css";
import { bricolageGrotesque } from "@/lib/fonts";
import QueryProvider from "@/config/tanstack/QueryProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${bricolageGrotesque.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <div className="relative z-10 flex min-h-full flex-1 flex-col">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
